# Generated by Django 5.2.5 on 2025-11-06 11:40

import django.utils.timezone
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0129_fix_script_paths'),
        ('netbox_licenses', '0006_currency_conversion_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyconversionrate',
            options={'ordering': ['currency_code']},
        ),
        migrations.RemoveIndex(
            model_name='currencyconversionrate',
            name='netbox_lice_from_cu_7a8c8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='currencyconversionrate',
            name='netbox_lice_source_fd8b29_idx',
        ),
        migrations.RenameField(
            model_name='currencyconversionrate',
            old_name='rate',
            new_name='rate_to_nok',
        ),
        migrations.RemoveField(
            model_name='currencyconversionrate',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='currencyconversionrate',
            name='to_currency',
        ),
        migrations.RenameField(
            model_name='currencyconversionrate',
            old_name='from_currency',
            new_name='currency_code',
        ),
        migrations.AddField(
            model_name='currencyconversionrate',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='currencyconversionrate',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='currencyconversionrate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='currencyconversionrate',
            index=models.Index(fields=['currency_code'], name='netbox_lice_currenc_e6432f_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyconversionrate',
            index=models.Index(fields=['source', '-last_updated'], name='netbox_lice_source_131a37_idx'),
        ),
    ]
