# Generated by Django 5.2.5 on 2025-11-06 13:33

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0129_fix_script_paths'),
        ('netbox_licenses', '0007_alter_currencyconversionrate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversionrate',
            name='currency_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('utilization_warning_threshold', models.IntegerField(default=80)),
                ('utilization_critical_threshold', models.IntegerField(default=95)),
                ('underutilization_threshold', models.IntegerField(default=20)),
                ('currency_sync_enabled', models.BooleanField(default=True)),
                ('currency_sync_interval_hours', models.IntegerField(default=24)),
                ('currency_stale_days', models.IntegerField(default=7)),
                ('renewal_warning_days', models.IntegerField(default=90)),
                ('renewal_critical_days', models.IntegerField(default=30)),
                ('enable_cost_tracking', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Plugin Configuration',
                'verbose_name_plural': 'Plugin Configuration',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
