# Generated by Django 5.2.5 on 2025-11-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_licenses', '0008_alter_currencyconversionrate_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='custom_field_data',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='tags',
        ),
    ]
