# Generated by Django 5.2.5 on 2025-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_licenses', '0009_remove_pluginconfiguration_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='enable_cost_tracking',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='underutilization_threshold',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='utilization_critical_threshold',
        ),
        migrations.RemoveField(
            model_name='pluginconfiguration',
            name='utilization_warning_threshold',
        ),
        migrations.AddField(
            model_name='pluginconfiguration',
            name='utilization_excellent_threshold',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='pluginconfiguration',
            name='utilization_good_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='pluginconfiguration',
            name='utilization_moderate_threshold',
            field=models.IntegerField(default=50),
        ),
    ]
